### ISSUE TITLE
Телефонная авторизация

### ISSUE THREAD

**Issue by solkin** [solkin/mandarin-android#93]
Новое окно первого входа, переработанное окно добавления последующих учётных записей, возможность входить по номеру телефона или логину и паролю.
Также необходимо предусмотреть обновление токена при его протухании.

**Comment by solkin** [comment]
Обновление токена также готово 7929073de796659fedcc97172f0649e361af2451

**Comment by m1kc** [comment]
Ты так упорно не хочешь пользоваться автозакрытием карточек, что я аж поражаюсь.
