### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by IzzySoft** [solkin/mandarin-android#98]
Could you please clarify what license this project is using, @solkin?

**Comment by IzzySoft** [comment]
@solkin any chance?

**Comment by solkin** [comment]
@IzzySoft Wow, sorry for delay. Mandarin is under MIT license. 9af3945b3aa30b8f215c3528c5e2d550e89776e1

**Comment by IzzySoft** [comment]
@solkin Thanks! Updated. Should show up [here](https://apt.izzysoft.de/fdroid/index/apk/com.tomclaw.mandarin) within 24h (with the next sync).

**Comment by solkin** [comment]
Thanks :)
