### ISSUE TITLE
v1.9.7 vs 1.1.6

### ISSUE THREAD

**Issue by marcdw1289** [solkin/mandarin-android#99]
GitHub/F-Droid has version 1.9.7 from 2018. Play Store has version 1.1.6 from 2020.
Mismatched versioning confuses me. Are they equivalent, is one actually newer than the other? I assume the Play Store version is recommended for newer devices.

**Comment by solkin** [comment]
There is 1.16 (not 1.1.6) in Google Play. So, it is more newer than 1.9.7

**Comment by marcdw1289** [comment]
Oh my goodness. My font is too small (in Aurora Store on the phone I was using) and my eyes too old.
Thanks for the correction. Guess I'll use the Play Store version.
